### ISSUE TITLE
safari issue

### ISSUE THREAD

**Issue by YongjunKang** [shapespark/shapespark-viewer-api#11]
<img width="978" alt="스크린샷 2022-05-16 오후 6 20 45" src="https://user-images.githubusercontent.com/67675376/168561215-c3c33472-2d29-4481-b41e-d7cddf69dec6.png">

After adding bundles to the project, the corresponding error occurs randomly when testing with safari.

When I unpacked and read the code in the walk.min.js, I found that '_asyncPropertiesDetectionListeners' code was not defined anywhere.

```js
    this.onAsyncPropertiesDetected = function (h) {
      void 0 !== e.webp ? h() : this._asyncPropertiesDetectionListeners.push(h);
    };
```

I changed the code as below. The error has been resolved.

```js
    this.onAsyncPropertiesDetected = function (h) {
      h();
    };
```

Is the code a problem?
It may not be accurate by referring to the translator.

**Comment by wmatyjewicz** [comment]
Thanks for the detailed report! We’ve identified the issue and implemented a fix. For scenes hosted on our infrastructure a viewer update with the fix will be rolled out this week. For bundling the fix will be included in the release of the Shapespark.

If you need to apply the fix for the bundles before the release, modify the code in the following way:
```
    this.onAsyncPropertiesDetected = function (h) {
      void 0 !== e.webp ? h() : _asyncPropertiesDetectionListeners.push(h);
    };

```
